#!/usr/bin/env python
# ---------------------------------------------------------------------------- #

import sys
from thrift.transport import TTransport
from thrift.transport import TSocket
from thrift.transport import THttpClient
from thrift.protocol import TBinaryProtocol
from ttypes import *
import RushHour
from dijkstra import shortestPath, Dijkstra


START = 'I-START'
FINISH = 'I-FINISH'


def road_time(distance, speed):
    try:
        x = (float(distance) / float(speed))
    except ZeroDivisionError:
        return float(sys.maxint)
    else:
        return x


def next_intersection(roadmap,dist,src):
    road_to_take = None 
    cheapest = sys.maxint
    dst = src
    for intersection in roadmap.Intersections:
        for road in intersection.ConnectedRoads:
            start = road.StartIntersection
            end = road.EndIntersection
            candidate = src
            if src == start:
                candidate = end
            elif src == end:
                candidate = start
            else:
                continue
            combined = dist[candidate] + road_time(road.Distance,
                    road.CurrentSpeed)
            if combined < cheapest:
                cheapest = combined
                road_to_take = road            
                dst = candidate
    return road_to_take,dst


def load(roadmap):
    g = {}
    for intersection in roadmap.Intersections:
        for road in intersection.ConnectedRoads:
            start = road.StartIntersection
            end = road.EndIntersection
            road_t = road_time(road.Distance,road.MaxSpeed)
            if start in g:
                g[start][end] = road_t
            else:
                g[start] = { end: road_t }
            if end in g:
                g[end][start] = road_t
            else:
                g[end] = { start: road_t }
    return g


#host = "thriftpuzzle.facebook.com"
host = "69.63.177.200"
port = 9032

socket = TSocket.TSocket(host, port)
transport = TTransport.TBufferedTransport(socket)
protocol = TBinaryProtocol.TBinaryProtocol(transport)
client = RushHour.Client(protocol)
transport.open()

if not client.registerClient('mlbright@gmail.com', 'Martin-Louis Bright'):
    sys.stderr.write("WTF: Could not register.\n")
    sys.exit(1)

current = START
while True:
    roadmap = client.getRoadConditions()
    G = load(roadmap)
    dist,prev = Dijkstra(G,FINISH)
    road,current = next_intersection(roadmap,dist,current)
    client.takeRoad(road,road.CurrentSpeed)
    print "name: %s, from %s to %s, time %.2f" % (road.Name,
        road.StartIntersection, road.EndIntersection, client.getTime())
    if current == FINISH:
        break

#print client.winGame()
transport.close()
